@startuml
abstract class	body	 #red	
body	 --|> 	bind_expr	
function_decl	 --|> 	body	
abstract class	type	 #red	
type	 --|> 	void_type	
bind_expr	 --|> 	type	
body	 --|> 	return_expr	
bind_expr	 --|> 	body	
body	 --|> 	statement_list	
abstract class	value	 #red	
value	 --|> 	bind_expr	
integer_cst	 --|> 	value	
body	 --|> 	call_expr	
abstract class	init	 #red	
init	 --|> 	bind_expr	
target_expr	 --|> 	init	
abstract class	vars	 #red	
vars	 --|> 	type_decl	
bind_expr	 --|> 	vars	
vars	 --|> 	var_decl	
body	 --|> 	cond_expr	
body	 --|> 	modify_expr	
abstract class	OP	 #red	
OP	 --|> 	bind_expr	
cond_expr	 --|> 	OP	
abstract class	E	 #red	
E	 --|> 	bind_expr	
statement_list	 --|> 	E	
body	 --|> 	asm_expr	
body	 --|> 	convert_expr	
@enduml
