@startuml
abstract class	type	 #red	
type	 --|> 	complex_type	
type_decl	 --|> 	type	
abstract class	name	 #red	
name	 --|> 	type_decl	
complex_type	 --|> 	name	
abstract class	size	 #red	
size	 --|> 	integer_cst	
complex_type	 --|> 	size	
abstract class	value	 #red	
value	 --|> 	complex_type	
integer_cst	 --|> 	value	
abstract class	valu	 #red	
valu	 --|> 	complex_type	
tree_list	 --|> 	valu	
abstract class	retn	 #red	
retn	 --|> 	complex_type	
function_type	 --|> 	retn	
@enduml
