@startuml
abstract class	OP	 #red	
OP	 --|> 	float_expr	
rdiv_expr	 --|> 	OP	
abstract class	type	 #red	
type	 --|> 	real_type	
float_expr	 --|> 	type	
OP	 --|> 	minus_expr	
float_expr	 --|> 	OP	
@enduml
