@startuml
abstract class	E	 #red	
E	 --|> 	preincrement_expr	
statement_list	 --|> 	E	
abstract class	type	 #red	
type	 --|> 	integer_type	
preincrement_expr	 --|> 	type	
abstract class	OP	 #red	
OP	 --|> 	var_decl	
preincrement_expr	 --|> 	OP	
OP	 --|> 	integer_cst	
@enduml
