@startuml
decl	 --|> 	identifier_node	 : 	name
decl	 --|> 	type	 : 	type
decl	 --|> 	decl	 : 	chain
type	 --|> 	decl	 : 	name
type	 --|> 	cst	 : 	size
type	 --|> 	cst	 : 	min
type	 --|> 	cst	 : 	max
cst	 --|> 	type	 : 	type
cst	 --|> 	decl	 : 	value
type	 --|> 	identifier_node	 : 	name
cst	 --|> 	identifier_node	 : 	value
cst	 --|> 	cst	 : 	value
cst	 --|> 	type	 : 	value
type	 --|> 	type	 : 	unql
type	 --|> 	type	 : 	elts
type	 --|> 	type	 : 	domn
type	 --|> 	decl	 : 	flds
type	 --|> 	type	 : 	ptd
decl	 --|> 	type	 : 	scpe
decl	 --|> 	cst	 : 	size
decl	 --|> 	cst	 : 	bpos
decl	 --|> 	identifier_node	 : 	mngl
decl	 --|> 	decl	 : 	scpe
type	 --|> 	type	 : 	retn
type	 --|> 	tree_list	 : 	prms
tree_list	 --|> 	type	 : 	valu
tree_list	 --|> 	tree_list	 : 	chan
type	 --|> 	tree_list	 : 	csts
decl	 --|> 	cst	 : 	cnst
tree_list	 --|> 	identifier_node	 : 	purp
tree_list	 --|> 	cst	 : 	valu
cst	 --|> 	modify_expr	 : 	value
decl	 --|> 	decl	 : 	args
decl	 --|> 	bind_expr	 : 	body
decl	 --|> 	type	 : 	argt
decl	 --|> 	decl	 : 	used
bind_expr	 --|> 	type	 : 	type
bind_expr	 --|> 	return_expr	 : 	body
return_expr	 --|> 	type	 : 	type
return_expr	 --|> 	modify_expr	 : 	expr
modify_expr	 --|> 	type	 : 	type
modify_expr	 --|> 	decl	 : 	OP
modify_expr	 --|> 	nop_expr	 : 	OP
nop_expr	 --|> 	type	 : 	type
nop_expr	 --|> 	call_expr	 : 	OP
call_expr	 --|> 	type	 : 	type
call_expr	 --|> 	addr_expr	 : 	fn
call_expr	 --|> 	nop_expr	 : 	E
call_expr	 --|> 	decl	 : 	E
addr_expr	 --|> 	type	 : 	type
addr_expr	 --|> 	decl	 : 	OP
nop_expr	 --|> 	decl	 : 	OP
bind_expr	 --|> 	list	 : 	body
list	 --|> 	switch_expr	 : 	E
list	 --|> 	label_expr	 : 	E
switch_expr	 --|> 	type	 : 	type
switch_expr	 --|> 	decl	 : 	cond
switch_expr	 --|> 	list	 : 	body
label_expr	 --|> 	type	 : 	type
label_expr	 --|> 	decl	 : 	name
list	 --|> 	case_label_expr	 : 	E
list	 --|> 	modify_expr	 : 	E
list	 --|> 	goto_expr	 : 	E
list	 --|> 	asm_expr	 : 	E
list	 --|> 	call_expr	 : 	E
cst	 --|> 	bind_expr	 : 	value
modify_expr	 --|> 	call_expr	 : 	OP
case_label_expr	 --|> 	type	 : 	type
case_label_expr	 --|> 	decl	 : 	name
case_label_expr	 --|> 	cst	 : 	low
modify_expr	 --|> 	ref	 : 	OP
goto_expr	 --|> 	type	 : 	type
goto_expr	 --|> 	decl	 : 	labl
asm_expr	 --|> 	type	 : 	type
call_expr	 --|> 	cst	 : 	E
ref	 --|> 	type	 : 	type
ref	 --|> 	nop_expr	 : 	OP
modify_expr	 --|> 	ne_expr	 : 	OP
ne_expr	 --|> 	type	 : 	type
ne_expr	 --|> 	call_expr	 : 	OP
ne_expr	 --|> 	cst	 : 	OP
call_expr	 --|> 	call_expr	 : 	E
nop_expr	 --|> 	addr_expr	 : 	OP
addr_expr	 --|> 	cst	 : 	OP
list	 --|> 	cond_expr	 : 	E
list	 --|> 	return_expr	 : 	E
cond_expr	 --|> 	type	 : 	type
cond_expr	 --|> 	truth_andif_expr	 : 	OP
cond_expr	 --|> 	return_expr	 : 	OP
truth_andif_expr	 --|> 	type	 : 	type
truth_andif_expr	 --|> 	ne_expr	 : 	OP
truth_andif_expr	 --|> 	truth_orif_expr	 : 	OP
cst	 --|> 	tree_list	 : 	value
truth_orif_expr	 --|> 	type	 : 	type
truth_orif_expr	 --|> 	eq_expr	 : 	OP
truth_orif_expr	 --|> 	lt_expr	 : 	OP
eq_expr	 --|> 	type	 : 	type
eq_expr	 --|> 	call_expr	 : 	OP
eq_expr	 --|> 	cst	 : 	OP
lt_expr	 --|> 	type	 : 	type
lt_expr	 --|> 	call_expr	 : 	OP
lt_expr	 --|> 	nop_expr	 : 	OP
modify_expr	 --|> 	cond_expr	 : 	OP
cond_expr	 --|> 	ne_expr	 : 	OP
cond_expr	 --|> 	call_expr	 : 	OP
cond_expr	 --|> 	nop_expr	 : 	OP
nop_expr	 --|> 	nop_expr	 : 	OP
call_expr	 --|> 	ge_expr	 : 	E
nop_expr	 --|> 	convert_expr	 : 	OP
nop_expr	 --|> 	modify_expr	 : 	OP
ge_expr	 --|> 	type	 : 	type
ge_expr	 --|> 	ref	 : 	OP
convert_expr	 --|> 	type	 : 	type
convert_expr	 --|> 	decl	 : 	OP
modify_expr	 --|> 	convert_expr	 : 	OP
ref	 --|> 	ref	 : 	OP
ref	 --|> 	decl	 : 	OP
ref	 --|> 	postincrement_expr	 : 	OP
cond_expr	 --|> 	gt_expr	 : 	OP
cond_expr	 --|> 	list	 : 	OP
cond_expr	 --|> 	le_expr	 : 	OP
cst	 --|> 	return_expr	 : 	value
postincrement_expr	 --|> 	type	 : 	type
postincrement_expr	 --|> 	ref	 : 	OP
postincrement_expr	 --|> 	cst	 : 	OP
gt_expr	 --|> 	type	 : 	type
gt_expr	 --|> 	call_expr	 : 	OP
gt_expr	 --|> 	cst	 : 	OP
le_expr	 --|> 	type	 : 	type
le_expr	 --|> 	call_expr	 : 	OP
le_expr	 --|> 	cst	 : 	OP
truth_andif_expr	 --|> 	le_expr	 : 	OP
truth_orif_expr	 --|> 	ne_expr	 : 	OP
ne_expr	 --|> 	bit_and_expr	 : 	OP
eq_expr	 --|> 	bit_and_expr	 : 	OP
bit_and_expr	 --|> 	type	 : 	type
bit_and_expr	 --|> 	decl	 : 	OP
bit_and_expr	 --|> 	cst	 : 	OP
bind_expr	 --|> 	call_expr	 : 	body
call_expr	 --|> 	ref	 : 	E
list	 --|> 	target_expr	 : 	E
target_expr	 --|> 	type	 : 	type
target_expr	 --|> 	decl	 : 	decl
target_expr	 --|> 	bind_expr	 : 	init
bind_expr	 --|> 	decl	 : 	vars
modify_expr	 --|> 	cst	 : 	OP
list	 --|> 	decl_expr	 : 	E
decl	 --|> 	constructor	 : 	init
decl_expr	 --|> 	type	 : 	type
convert_expr	 --|> 	call_expr	 : 	OP
addr_expr	 --|> 	ref	 : 	OP
modify_expr	 --|> 	eq_expr	 : 	OP
decl	 --|> 	ref	 : 	init
eq_expr	 --|> 	nop_expr	 : 	OP
eq_expr	 --|> 	decl	 : 	OP
nop_expr	 --|> 	ref	 : 	OP
cond_expr	 --|> 	eq_expr	 : 	OP
modify_expr	 --|> 	truth_andif_expr	 : 	OP
truth_andif_expr	 --|> 	eq_expr	 : 	OP
bind_expr	 --|> 	cond_expr	 : 	body
eq_expr	 --|> 	ref	 : 	OP
truth_andif_expr	 --|> 	truth_andif_expr	 : 	OP
ne_expr	 --|> 	ref	 : 	OP
ne_expr	 --|> 	decl	 : 	OP
cond_expr	 --|> 	modify_expr	 : 	OP
modify_expr	 --|> 	addr_expr	 : 	OP
bind_expr	 --|> 	modify_expr	 : 	body
cond_expr	 --|> 	lt_expr	 : 	OP
eq_expr	 --|> 	addr_expr	 : 	OP
decl	 --|> 	cst	 : 	init
cond_expr	 --|> 	ge_expr	 : 	OP
modify_expr	 --|> 	plus_expr	 : 	OP
ge_expr	 --|> 	nop_expr	 : 	OP
ge_expr	 --|> 	cst	 : 	OP
modify_expr	 --|> 	rshift_expr	 : 	OP
plus_expr	 --|> 	type	 : 	type
plus_expr	 --|> 	decl	 : 	OP
plus_expr	 --|> 	cst	 : 	OP
modify_expr	 --|> 	lshift_expr	 : 	OP
rshift_expr	 --|> 	type	 : 	type
rshift_expr	 --|> 	decl	 : 	OP
rshift_expr	 --|> 	cst	 : 	OP
lshift_expr	 --|> 	type	 : 	type
lshift_expr	 --|> 	decl	 : 	OP
lshift_expr	 --|> 	cst	 : 	OP
nop_expr	 --|> 	plus_expr	 : 	OP
plus_expr	 --|> 	convert_expr	 : 	OP
modify_expr	 --|> 	bit_ior_expr	 : 	OP
call_expr	 --|> 	addr_expr	 : 	E
modify_expr	 --|> 	bit_and_expr	 : 	OP
ref	 --|> 	pointer_plus_expr	 : 	OP
bit_ior_expr	 --|> 	type	 : 	type
bit_ior_expr	 --|> 	ref	 : 	OP
bit_ior_expr	 --|> 	lshift_expr	 : 	OP
decl	 --|> 	lshift_expr	 : 	init
bit_and_expr	 --|> 	ref	 : 	OP
bit_and_expr	 --|> 	bit_not_expr	 : 	OP
pointer_plus_expr	 --|> 	type	 : 	type
pointer_plus_expr	 --|> 	decl	 : 	OP
pointer_plus_expr	 --|> 	nop_expr	 : 	OP
lshift_expr	 --|> 	trunc_mod_expr	 : 	OP
decl	 --|> 	pointer_plus_expr	 : 	init
bit_not_expr	 --|> 	type	 : 	type
bit_not_expr	 --|> 	lshift_expr	 : 	OP
nop_expr	 --|> 	mult_expr	 : 	OP
trunc_mod_expr	 --|> 	type	 : 	type
trunc_mod_expr	 --|> 	decl	 : 	OP
trunc_mod_expr	 --|> 	cst	 : 	OP
bit_ior_expr	 --|> 	decl	 : 	OP
mult_expr	 --|> 	type	 : 	type
mult_expr	 --|> 	nop_expr	 : 	OP
mult_expr	 --|> 	cst	 : 	OP
modify_expr	 --|> 	bit_xor_expr	 : 	OP
nop_expr	 --|> 	save_expr	 : 	OP
bit_xor_expr	 --|> 	type	 : 	type
bit_xor_expr	 --|> 	ref	 : 	OP
bit_xor_expr	 --|> 	decl	 : 	OP
bit_not_expr	 --|> 	decl	 : 	OP
save_expr	 --|> 	type	 : 	type
save_expr	 --|> 	trunc_div_expr	 : 	OP
nop_expr	 --|> 	trunc_div_expr	 : 	OP
trunc_div_expr	 --|> 	type	 : 	type
trunc_div_expr	 --|> 	decl	 : 	OP
trunc_div_expr	 --|> 	cst	 : 	OP
nop_expr	 --|> 	postincrement_expr	 : 	OP
bit_and_expr	 --|> 	nop_expr	 : 	OP
cond_expr	 --|> 	truth_orif_expr	 : 	OP
cond_expr	 --|> 	cst	 : 	OP
nop_expr	 --|> 	rshift_expr	 : 	OP
truth_orif_expr	 --|> 	le_expr	 : 	OP
gt_expr	 --|> 	nop_expr	 : 	OP
rshift_expr	 --|> 	ref	 : 	OP
rshift_expr	 --|> 	bit_and_expr	 : 	OP
le_expr	 --|> 	decl	 : 	OP
bit_ior_expr	 --|> 	rshift_expr	 : 	OP
plus_expr	 --|> 	plus_expr	 : 	OP
bit_and_expr	 --|> 	negate_expr	 : 	OP
call_expr	 --|> 	convert_expr	 : 	E
plus_expr	 --|> 	nop_expr	 : 	OP
cond_expr	 --|> 	bind_expr	 : 	OP
negate_expr	 --|> 	type	 : 	type
negate_expr	 --|> 	decl	 : 	OP
plus_expr	 --|> 	ne_expr	 : 	OP
le_expr	 --|> 	mult_expr	 : 	OP
decl	 --|> 	mult_expr	 : 	init
list	 --|> 	bind_expr	 : 	E
list	 --|> 	predecrement_expr	 : 	E
truth_orif_expr	 --|> 	truth_orif_expr	 : 	OP
truth_orif_expr	 --|> 	gt_expr	 : 	OP
le_expr	 --|> 	bit_ior_expr	 : 	OP
mult_expr	 --|> 	decl	 : 	OP
decl	 --|> 	nop_expr	 : 	init
predecrement_expr	 --|> 	type	 : 	type
predecrement_expr	 --|> 	decl	 : 	OP
predecrement_expr	 --|> 	cst	 : 	OP
cond_expr	 --|> 	goto_expr	 : 	OP
gt_expr	 --|> 	bit_ior_expr	 : 	OP
decl	 --|> 	call_expr	 : 	init
trunc_div_expr	 --|> 	nop_expr	 : 	OP
postincrement_expr	 --|> 	decl	 : 	OP
nop_expr	 --|> 	minus_expr	 : 	OP
minus_expr	 --|> 	type	 : 	type
minus_expr	 --|> 	convert_expr	 : 	OP
minus_expr	 --|> 	nop_expr	 : 	OP
gt_expr	 --|> 	mult_expr	 : 	OP
lt_expr	 --|> 	decl	 : 	OP
lt_expr	 --|> 	cst	 : 	OP
modify_expr	 --|> 	trunc_div_expr	 : 	OP
modify_expr	 --|> 	pointer_plus_expr	 : 	OP
cond_expr	 --|> 	cond_expr	 : 	OP
trunc_div_expr	 --|> 	plus_expr	 : 	OP
call_expr	 --|> 	decl	 : 	fn
gt_expr	 --|> 	decl	 : 	OP
bind_expr	 --|> 	asm_expr	 : 	body
bind_expr	 --|> 	bind_expr	 : 	body
nop_expr	 --|> 	target_expr	 : 	OP
modify_expr	 --|> 	target_expr	 : 	OP
decl	 --|> 	decl	 : 	init
switch_expr	 --|> 	cst	 : 	cond
modify_expr	 --|> 	minus_expr	 : 	OP
call_expr	 --|> 	eq_expr	 : 	E
nop_expr	 --|> 	cst	 : 	OP
minus_expr	 --|> 	decl	 : 	OP
lt_expr	 --|> 	trunc_div_expr	 : 	OP
trunc_div_expr	 --|> 	call_expr	 : 	OP
call_expr	 --|> 	trunc_div_expr	 : 	E
minus_expr	 --|> 	ref	 : 	OP
nop_expr	 --|> 	bit_ior_expr	 : 	OP
bit_ior_expr	 --|> 	nop_expr	 : 	OP
bit_ior_expr	 --|> 	bit_ior_expr	 : 	OP
nop_expr	 --|> 	lshift_expr	 : 	OP
nop_expr	 --|> 	lrotate_expr	 : 	OP
bit_ior_expr	 --|> 	bit_and_expr	 : 	OP
rshift_expr	 --|> 	nop_expr	 : 	OP
lshift_expr	 --|> 	nop_expr	 : 	OP
lrotate_expr	 --|> 	type	 : 	type
lrotate_expr	 --|> 	nop_expr	 : 	OP
lrotate_expr	 --|> 	cst	 : 	OP
bit_and_expr	 --|> 	rshift_expr	 : 	OP
bit_and_expr	 --|> 	lshift_expr	 : 	OP
cst	 --|> 	addr_expr	 : 	value
cst	 --|> 	call_expr	 : 	value
cst	 --|> 	eq_expr	 : 	value
cst	 --|> 	ne_expr	 : 	value
convert_expr	 --|> 	ref	 : 	OP
ref	 --|> 	plus_expr	 : 	OP
plus_expr	 --|> 	mult_expr	 : 	OP
mult_expr	 --|> 	ref	 : 	OP
gt_expr	 --|> 	ref	 : 	OP
pointer_plus_expr	 --|> 	ref	 : 	OP
plus_expr	 --|> 	minus_expr	 : 	OP
cst	 --|> 	plus_expr	 : 	value
cst	 --|> 	nop_expr	 : 	value
cst	 --|> 	bit_and_expr	 : 	value
return_expr	 --|> 	call_expr	 : 	expr
call_expr	 --|> 	ref	 : 	fn
ref	 --|> 	call_expr	 : 	OP
nop_expr	 --|> 	truth_andif_expr	 : 	OP
decl	 --|> 	target_expr	 : 	init
nop_expr	 --|> 	truth_not_expr	 : 	OP
truth_not_expr	 --|> 	type	 : 	type
truth_not_expr	 --|> 	ref	 : 	OP
truth_andif_expr	 --|> 	gt_expr	 : 	OP
le_expr	 --|> 	ref	 : 	OP
lt_expr	 --|> 	ref	 : 	OP
nop_expr	 --|> 	truth_orif_expr	 : 	OP
ref	 --|> 	cst	 : 	OP
pointer_plus_expr	 --|> 	cst	 : 	OP
call_expr	 --|> 	ne_expr	 : 	E
truth_andif_expr	 --|> 	nop_expr	 : 	OP
truth_orif_expr	 --|> 	truth_andif_expr	 : 	OP
truth_not_expr	 --|> 	call_expr	 : 	OP
pointer_plus_expr	 --|> 	negate_expr	 : 	OP
negate_expr	 --|> 	nop_expr	 : 	OP
bind_expr	 --|> 	convert_expr	 : 	body
list	 --|> 	postincrement_expr	 : 	E
call_expr	 --|> 	pointer_plus_expr	 : 	E
ne_expr	 --|> 	nop_expr	 : 	OP
gt_expr	 --|> 	plus_expr	 : 	OP
lt_expr	 --|> 	minus_expr	 : 	OP
cond_expr	 --|> 	convert_expr	 : 	OP
bit_and_expr	 --|> 	plus_expr	 : 	OP
nop_expr	 --|> 	pointer_plus_expr	 : 	OP
list	 --|> 	convert_expr	 : 	E
convert_expr	 --|> 	cst	 : 	OP
plus_expr	 --|> 	ref	 : 	OP
nop_expr	 --|> 	min_expr	 : 	OP
min_expr	 --|> 	type	 : 	type
min_expr	 --|> 	decl	 : 	OP
min_expr	 --|> 	cst	 : 	OP
call_expr	 --|> 	minus_expr	 : 	E
ne_expr	 --|> 	target_expr	 : 	OP
decl	 --|> 	ne_expr	 : 	init
call_expr	 --|> 	mult_expr	 : 	E
mult_expr	 --|> 	trunc_div_expr	 : 	OP
ne_expr	 --|> 	modify_expr	 : 	OP
ne_expr	 --|> 	pointer_plus_expr	 : 	OP
modify_expr	 --|> 	modify_expr	 : 	OP
bit_and_expr	 --|> 	bit_and_expr	 : 	OP
bit_and_expr	 --|> 	cond_expr	 : 	OP
ge_expr	 --|> 	decl	 : 	OP
cond_expr	 --|> 	plus_expr	 : 	OP
plus_expr	 --|> 	lshift_expr	 : 	OP
decl	 --|> 	addr_expr	 : 	init
lshift_expr	 --|> 	bit_and_expr	 : 	OP
list	 --|> 	predict_expr	 : 	E
predict_expr	 --|> 	type	 : 	type
decl	 --|> 	cond_expr	 : 	init
ne_expr	 --|> 	save_expr	 : 	OP
decl	 --|> 	convert_expr	 : 	init
save_expr	 --|> 	ref	 : 	OP
convert_expr	 --|> 	trunc_div_expr	 : 	OP
mult_expr	 --|> 	plus_expr	 : 	OP
call_expr	 --|> 	plus_expr	 : 	E
call_expr	 --|> 	bit_and_expr	 : 	E
nop_expr	 --|> 	bit_not_expr	 : 	OP
bit_not_expr	 --|> 	ref	 : 	OP
modify_expr	 --|> 	compound_literal_expr	 : 	OP
modify_expr	 --|> 	negate_expr	 : 	OP
compound_literal_expr	 --|> 	type	 : 	type
trunc_div_expr	 --|> 	ref	 : 	OP
negate_expr	 --|> 	ref	 : 	OP
decl	 --|> 	eq_expr	 : 	init
modify_expr	 --|> 	max_expr	 : 	OP
call_expr	 --|> 	postincrement_expr	 : 	E
max_expr	 --|> 	type	 : 	type
max_expr	 --|> 	decl	 : 	OP
truth_andif_expr	 --|> 	lt_expr	 : 	OP
mult_expr	 --|> 	postincrement_expr	 : 	OP
decl	 --|> 	ge_expr	 : 	init
truth_orif_expr	 --|> 	nop_expr	 : 	OP
pointer_plus_expr	 --|> 	plus_expr	 : 	OP
list	 --|> 	postdecrement_expr	 : 	E
list	 --|> 	preincrement_expr	 : 	E
call_expr	 --|> 	cond_expr	 : 	E
postdecrement_expr	 --|> 	type	 : 	type
postdecrement_expr	 --|> 	decl	 : 	OP
postdecrement_expr	 --|> 	cst	 : 	OP
modify_expr	 --|> 	rdiv_expr	 : 	OP
preincrement_expr	 --|> 	type	 : 	type
preincrement_expr	 --|> 	decl	 : 	OP
preincrement_expr	 --|> 	cst	 : 	OP
switch_expr	 --|> 	ref	 : 	cond
plus_expr	 --|> 	call_expr	 : 	OP
list	 --|> 	compound_expr	 : 	E
le_expr	 --|> 	nop_expr	 : 	OP
modify_expr	 --|> 	mult_expr	 : 	OP
rdiv_expr	 --|> 	type	 : 	type
rdiv_expr	 --|> 	float_expr	 : 	OP
rdiv_expr	 --|> 	cst	 : 	OP
switch_expr	 --|> 	nop_expr	 : 	cond
compound_expr	 --|> 	type	 : 	type
compound_expr	 --|> 	modify_expr	 : 	OP
compound_expr	 --|> 	postincrement_expr	 : 	OP
plus_expr	 --|> 	bit_and_expr	 : 	OP
float_expr	 --|> 	type	 : 	type
float_expr	 --|> 	minus_expr	 : 	OP
truth_orif_expr	 --|> 	ge_expr	 : 	OP
compound_expr	 --|> 	save_expr	 : 	OP
cond_expr	 --|> 	compound_expr	 : 	OP
eq_expr	 --|> 	predecrement_expr	 : 	OP
decl	 --|> 	plus_expr	 : 	init
minus_expr	 --|> 	cst	 : 	OP
minus_expr	 --|> 	bit_and_expr	 : 	OP
ne_expr	 --|> 	plus_expr	 : 	OP
save_expr	 --|> 	call_expr	 : 	OP
le_expr	 --|> 	plus_expr	 : 	OP
plus_expr	 --|> 	save_expr	 : 	OP
modify_expr	 --|> 	le_expr	 : 	OP
ref	 --|> 	bit_and_expr	 : 	OP
modify_expr	 --|> 	ge_expr	 : 	OP
type	 --|> 	type	 : 	refd
@enduml
